// Generated by CoffeeScript 1.3.3
(function() {
  var app, db, express, redis;

  express = require('express');

  redis = require('redis');

  db = redis.createClient();

  app = express();

  app.use(express.bodyParser({
    keepExtensions: true,
    uploadDir: __dirname + '/static/uploads'
  }));

  app.use(express["static"](__dirname + '/static'));

  app.set('views', __dirname + '/views');

  app.engine('html', require('ejs').renderFile);

  app.get('/', function(req, res) {
    return res.render('index.html');
  });

  app.post('/audioupload', function(req, res) {
    console.log(req.files);
    return res.render('index.html');
  });

  app.listen(3666);

}).call(this);
