// Generated by CoffeeScript 1.3.3
(function() {
  var $, delay, startAnimatic;

  $ = function(id) {
    return document.getElementById(id);
  };

  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

  window.onload = function() {
    window.frame_index = 0;
    window.animatic = [];
    window.frames = {};
    window.initCanvas();
    window.initTools();
    window.initTabs();
    window.initOnion();
    return $("audio").addEventListener("playing", function(e) {
      return startAnimatic();
    });
  };

  window.addFrame = function() {
    var frame, name, time;
    name = $("insert-pic-select").value;
    if (name) {
      time = window.animatic.length < 1 ? 0 : 300;
      frame = [time, name];
      window.animatic.push(frame);
      return drawTimeline(window.animatic);
    }
  };

  window.drawTimeline = function() {
    var chunk_td_duration, chunk_td_image, chunk_td_thumb, chunk_tr, delete_link, duration, duration_input, frame, frame_name, index, select, select_clone, thumb_img, timeline, _i, _len, _results;
    timeline = $("timeline-table");
    timeline.innerHTML = '<th>Thumb</th><th>Image</th><th>Relative Offset</th>';
    _results = [];
    for (index = _i = 0, _len = animatic.length; _i < _len; index = ++_i) {
      frame = animatic[index];
      if (frame !== null) {
        duration = frame[0];
        frame_name = frame[1];
        chunk_tr = document.createElement("tr");
        chunk_td_thumb = document.createElement("td");
        chunk_td_image = document.createElement("td");
        chunk_td_duration = document.createElement("td");
        thumb_img = document.createElement("img");
        thumb_img.id = "thumb-" + index;
        thumb_img.height = 75;
        thumb_img.width = 100;
        thumb_img.src = window.frames[frame_name];
        select = $("insert-pic-select");
        select_clone = select.cloneNode(true);
        select_clone.value = frame_name;
        select_clone.index = index;
        duration_input = document.createElement("input");
        duration_input.value = duration;
        duration_input.index = index;
        duration_input.type = 'number';
        delete_link = document.createElement("a");
        delete_link.innerText = "del";
        delete_link.href = "#";
        delete_link.index = index;
        chunk_td_thumb.appendChild(thumb_img);
        chunk_td_image.appendChild(select_clone);
        chunk_td_duration.appendChild(duration_input);
        chunk_td_duration.appendChild(delete_link);
        chunk_tr.appendChild(chunk_td_thumb);
        chunk_tr.appendChild(chunk_td_image);
        chunk_tr.appendChild(chunk_td_duration);
        select_clone.addEventListener("change", function() {
          var thumb;
          animatic[this.index][1] = this.value;
          thumb = $("thumb-" + this.index);
          return thumb.src = window.frames[this.value];
        });
        duration_input.addEventListener("blur", function() {
          return animatic[this.index][0] = parseInt(this.value);
        });
        delete_link.addEventListener("click", function() {
          window.animatic.splice(parseInt(this.index), 1);
          return drawTimeline();
        });
        _results.push(timeline.appendChild(chunk_tr));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  startAnimatic = function() {
    var file, frame, image, timeOffset, view, _i, _len, _results;
    timeOffset = 0;
    view = $("view");
    file = 1;
    _results = [];
    for (_i = 0, _len = animatic.length; _i < _len; _i++) {
      frame = animatic[_i];
      if (frame) {
        image = window.frames[frame[1]];
        _results.push((function(image) {
          timeOffset += frame[0];
          return delay(timeOffset, function() {
            return view.style.backgroundImage = "url('" + image + "')";
          });
        })(image));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

}).call(this);
